//
//  ScanLineDetermination.hpp
//  DigitScanner
//
//  Created by 王 颖豪 on 7/8/17.
//  Copyright © 2017 TSK. All rights reserved.
//

#ifndef ScanLineDetermination_hpp
#define ScanLineDetermination_hpp

#include "Contour.hpp"
#include <vector>
#include <algorithm>
#include "CImg.h"

using namespace cimg_library;
using namespace ct;

struct RectWLine
{
    int line;
    Rect rect;
};

inline bool rectSort(const RectWLine& r1, const RectWLine& r2)
{
    if (r1.line < r2.line)
        return true;
    else if (r1.line > r2.line)
        return false;
    else if (r1.rect.x < r2.rect.x)
        return true;
    else
        return false;
}

class ScanLineDet
{
public:
    ScanLineDet(int h) : height(h) {}
    
    /**
     *  getSorted():
     *  From a set of rects generated by contour
     *  detection, sort the rects by line and
     *  horizontal position.
     */
    vector<Rect> getSorted(vector<Rect> regions)
    {
        
        vector<int> lineRectHist;
        for (int i = 0; i < height; i++)
        {
            int vote = 0;
            for (auto& r : regions)
            {
                if (r.y <= i && r.y + r.height >= i)
                    vote++;
            }
            lineRectHist.push_back(vote);
        }
        
        vector<int> dLineRectHist;
        dLineRectHist.push_back(-1);
        for (int i = 1; i < lineRectHist.size(); i++)
        {
            dLineRectHist.push_back(lineRectHist[i] - lineRectHist[i-1]);
        }
        
        vector<int> medPair;
        int lo = -1, hi = -1;
        for (int i = 0 ; i < dLineRectHist.size(); i++)
        {
            
            if (dLineRectHist[i] > 0)
            {
                lo = i;
            }
            
            if (dLineRectHist[i] < 0 && lo != -1)
            {
                hi = i;
                medPair.push_back((lo + hi) / 2);
                lo = -1;
                hi = -1;
            }
        }
        
        vector<RectWLine> rectLinePairs;
        for (int i = 0; i < medPair.size(); i++)
        {
            for (int j = 0; j < regions.size(); j++)
            {
                if (regions[j].y <= medPair[i] && regions[j].y + regions[j].height >= medPair[i])
                {
                    RectWLine r;
                    r.line = medPair[i];
                    r.rect = regions[j];
                    rectLinePairs.push_back(r);
                }
            }
        }
        
        //Sort By Line Num;
        sort(rectLinePairs.begin(), rectLinePairs.end(), rectSort);
        
        vector<Rect> sorted;
        int lastLine = -1;
        for (auto rlp : rectLinePairs)
        {
            if (lastLine == -1)
            {
                lastLine = rlp.line;
            }
            else
            {
                if (lastLine != rlp.line)
                {
                    Rect delim(-1, -1, -1, -1);
                    sorted.push_back(delim);
                    lastLine = rlp.line;
                }
                
            }
            sorted.push_back(rlp.rect);
            
        }
        
        return sorted;
    }
    
    int height;
};

#endif /* ScanLineDetermination_hpp */
